//> using scala "3.2.1"
//> using options "--deprecation"
//> using options "--explain"
//> using options "-Yno-predef"
//> using lib "org.graalvm.sdk:graal-sdk:22.1.0"
//> using lib "org.typelevel::cats-effect:3.3.13"
